# Generated by Django 6.0.7 on 2026-08-24 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.filiere')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
