# Generated by Django 5.1.15 on 2026-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sitelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Forcer l'utilisateur à modifier son mot de passe dès sa prochaine connexion.",
                verbose_name="Doit modifier son mot de passe",
            ),
        ),
    ]
