# Generated by Django 5.1.15 on 2026-09-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_session_key",
            field=models.CharField(
                blank=True,
                help_text="Stocke la clé de session actuellement valide pour empêcher les connexions simultanées.",
                max_length=40,
                null=True,
                verbose_name="Clé de session active",
            ),
        ),
    ]
