# Generated by Django 5.1.15 on 2026-10-09 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_active_session_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(db_index=True, max_length=64)),
                ("device_name", models.CharField(default="Appareil", max_length=100)),
                ("ip_address", models.CharField(blank=True, max_length=45, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_login"],
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
