# Generated by Django 5.1.15 on 2026-10-10 18:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_devicerevocationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="avatars/",
            ),
        ),
    ]
