# Generated by Django 5.1.15 on 2026-09-02 13:33

import academics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_academicyear_options_alter_filiere_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="label",
            field=models.CharField(
                help_text="Année académique au format YYYY-YYYY (ex: 2025-2026)",
                max_length=20,
                unique=True,
                validators=[academics.models.validate_academic_year_format],
            ),
        ),
    ]
