# Generated by Django 5.1.15 on 2026-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_academicyear_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_free_correction",
            field=models.BooleanField(
                default=False,
                help_text="Si vrai, les corrigés et résumés de cette UE sont gratuits pour tous les étudiants.",
            ),
        ),
    ]
