# Generated by Django 5.1.15 on 2026-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_subject_is_free_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image représentative de la matière / UE (format carré ou paysage recommandé).",
                null=True,
                upload_to="subjects/",
                verbose_name="Image de couverture",
            ),
        ),
    ]
