# Generated by Django 5.1.15 on 2026-09-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_subject_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_students_count', models.PositiveIntegerField(default=5000, help_text='Valeur de base pour Étudiants inscrits')),
                ('base_exams_count', models.PositiveIntegerField(default=1200, help_text='Valeur de base pour Épreuves disponibles')),
                ('base_summaries_count', models.PositiveIntegerField(default=450, help_text='Valeur de base pour Résumés de cours')),
                ('base_schools_count', models.PositiveIntegerField(default=15, help_text='Valeur de base pour Écoles & Universités')),
                ('base_subjects_count', models.PositiveIntegerField(default=300, help_text='Valeur de base pour Matières clés')),
            ],
            options={
                'verbose_name': 'Configuration Globale (Statistiques)',
                'verbose_name_plural': 'Configuration Globale (Statistiques)',
            },
        ),
    ]
