# Generated by Django 5.1.15 on 2026-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_siteconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_exams_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Épreuves disponibles"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_schools_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Écoles & Universités"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_students_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Étudiants inscrits"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_subjects_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Matières clés"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_summaries_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Résumés de cours"
            ),
        ),
    ]
