<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-09-09 18:06

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.1.15 on 2026-09-09 17:27

>>>>>>> 178b2d431df2624058fc5dac2c3627328165af71
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_siteconfiguration"),
<<<<<<< HEAD
        ("exams", "0005_exam_is_free_correction_alter_exam_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 178b2d431df2624058fc5dac2c3627328165af71
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_exams_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Épreuves disponibles"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_schools_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Écoles & Universités"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_students_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Étudiants inscrits"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_subjects_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Matières clés"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="base_summaries_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Valeur de base pour Résumés de cours"
            ),
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name="SubjectConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subject_consultations",
                        to="exams.exam",
                        verbose_name="Épreuve consultée",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="academics.subject",
                        verbose_name="Matière / UE",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ue_consultations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation d'UE",
                "verbose_name_plural": "Consultations d'UE",
                "ordering": ["-created_at"],
            },
        ),
=======
>>>>>>> 178b2d431df2624058fc5dac2c3627328165af71
    ]
