# Generated by Django 5.1.15 on 2026-10-10 18:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_siteconfiguration_base_exams_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="logo",
            field=models.ImageField(
                blank=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="schools/",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image représentative de la matière / UE (format carré ou paysage recommandé).",
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="subjects/",
                verbose_name="Image de couverture",
            ),
        ),
    ]
