# Generated by Django 5.1.15 on 2026-08-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_EXAM", "Nouvelle Épreuve"),
                    ("NEW_CORRECTION", "Nouveau Corrigé"),
                    ("NEW_SUMMARY", "Nouveau Résumé"),
                    ("NEW_GUIDE", "Nouveau Guide"),
                    ("NEW_ADVICE", "Nouveau Conseil"),
                    ("PREMIUM", "Offre Premium"),
                    ("PAYMENT", "Paiement & Accès"),
                    ("SUPPORT_REPLY", "Réponse Support"),
                    ("SYSTEM", "Information Système"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
