# Generated by Django 5.1.15 on 2026-09-02 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="guest_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Adresse email (invité)",
            ),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="guest_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Nom complet (invité)",
            ),
        ),
        migrations.AlterField(
            model_name="supportrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Étudiant",
            ),
        ),
    ]
