# Generated by Django 5.1.15 on 2026-09-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "support",
            "0002_supportrequest_guest_email_supportrequest_guest_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportrequest",
            name="category",
            field=models.CharField(
                choices=[
                    ("recuperation_mot_de_passe", "Récupération de mot de passe"),
                    ("question", "Question"),
                    ("probleme_epreuve", "Problème avec une épreuve"),
                    ("probleme_compte", "Problème de compte"),
                    ("paiement", "Paiement"),
                    ("suggestion", "Suggestion"),
                    ("signaler_erreur", "Signaler une erreur"),
                    ("autre", "Autre"),
                ],
                default="question",
                max_length=30,
                verbose_name="Catégorie / Motif",
            ),
        ),
    ]
