# Generated by Django 5.1.15 on 2026-08-26 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_filiere_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('GENERAL', 'Conseil Général'), ('METHODOLOGY', 'Méthodologie de travail'), ('EXAM_PREP', 'Préparation aux Examens'), ('ORIENTATION', 'Orientation & Débouchés')], default='GENERAL', max_length=20)),
                ('summary', models.TextField(blank=True, help_text="Bref résumé de l'article")),
                ('content', models.TextField(help_text="Contenu rédigé de l'article")),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_REVIEW', 'En attente de relecture'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('target_filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='academics.filiere')),
                ('target_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='academics.school')),
                ('target_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('introduction', models.TextField(blank=True, help_text='Présentation générale du guide')),
                ('objectives', models.TextField(blank=True, help_text="Ce que l'étudiant doit maîtriser")),
                ('how_to_study', models.TextField(blank=True, help_text='Méthode de travail recommandée')),
                ('key_concepts', models.TextField(blank=True, help_text='Notions et concepts fondamentaux')),
                ('working_with_past_papers', models.TextField(blank=True, help_text='Comment traiter les anciennes épreuves')),
                ('common_mistakes', models.TextField(blank=True, help_text='Pièges courants à éviter')),
                ('exam_strategy', models.TextField(blank=True, help_text="Stratégie pour le jour de l'examen")),
                ('file', models.FileField(blank=True, help_text='Fichier PDF optionnel', null=True, upload_to='guides_pdf/')),
                ('access_type', models.CharField(choices=[('FREE', 'Gratuit'), ('PREMIUM', 'Premium')], default='FREE', max_length=10)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_REVIEW', 'En attente de relecture'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_guides', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('introduction', models.TextField(blank=True, help_text='Présentation succincte du résumé')),
                ('content', models.TextField(help_text='Contenu rédigé du résumé (HTML ou texte enrichi)')),
                ('file', models.FileField(blank=True, help_text='Version PDF optionnelle', null=True, upload_to='summaries_pdf/')),
                ('access_type', models.CharField(choices=[('FREE', 'Gratuit'), ('PREMIUM', 'Premium')], default='PREMIUM', max_length=10)),
                ('publication_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_REVIEW', 'En attente de relecture'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_summaries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='academics.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
