# Generated by Django 5.1.15 on 2026-08-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_academicyear_options_alter_filiere_options_and_more"),
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Titre du fichier"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Fichier PDF conservé dans le dépôt Cloud",
                        upload_to="cloud_library/%Y/%m/",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("EXAM", "Épreuve / Sujet"),
                            ("CORRECTION", "Correction / Corrigé"),
                            ("SUMMARY", "Fiche / Résumé"),
                            ("OTHER", "Autre Document"),
                        ],
                        default="EXAM",
                        max_length=20,
                        verbose_name="Type de ressource",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filiere",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_files",
                        to="academics.filiere",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_files",
                        to="academics.school",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_files",
                        to="academics.semester",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_cloud_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Fichier Cloud",
                "verbose_name_plural": "Fichiers Cloud",
                "ordering": ["-created_at"],
            },
        ),
    ]
