# Generated by Django 5.1.15 on 2026-09-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_cloudfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu ou note facultative du résumé",
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Document PDF du résumé",
                null=True,
                upload_to="summaries_pdf/",
            ),
        ),
        migrations.AlterField(
            model_name="summary",
            name="introduction",
            field=models.TextField(
                blank=True, default="", help_text="Présentation succincte du résumé"
            ),
        ),
    ]
