# Generated by Django 5.2.17 on 2026-10-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_alter_summary_content_alter_summary_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudfile",
            name="file",
            field=models.FileField(
                help_text="Fichier PDF conservé dans le dépôt Cloud",
                upload_to="cloud_library/%Y/",
            ),
        ),
    ]
