# Generated by Django 5.1.15 on 2026-10-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_organise_uploads_par_annee_academique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='file',
            field=models.FileField(blank=True, help_text="Document PDF du résumé — lié à l'UE, pas à une année académique", null=True, upload_to='summaries_pdf/'),
        ),
    ]
