# Generated by Django 5.1.15 on 2026-08-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_alter_academicyear_options_alter_filiere_options_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="XOF", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="external_reference",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="operator",
            field=models.CharField(
                choices=[
                    ("mtn", "MTN Money"),
                    ("moov", "Moov Money"),
                    ("celtiis", "Celtiis Money"),
                ],
                default="mtn",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="payment",
            name="sebpay_transaction_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="payment",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="academics.semester",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="semester_access",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.semesteraccess",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Payé / Réussi"),
                    ("REJECTED", "Rejeté / Échoué"),
                    ("EXPIRED", "Expiré"),
                    ("CANCELLED", "Annulé"),
                    ("en_attente", "En attente (ancien)"),
                    ("reussi", "Réussi (ancien)"),
                    ("echoue", "Échoué (ancien)"),
                    ("annule", "Annulé (ancien)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
