# Generated by Django 5.1.15 on 2026-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_options_payment_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Payé / Réussi"),
                    ("REJECTED", "Rejeté / Échoué"),
                    ("EXPIRED", "Expiré"),
                    ("CANCELLED", "Annulé"),
                    ("en_attente", "En attente (ancien)"),
                    ("reussi", "Réussi (ancien)"),
                    ("echoue", "Échoué (ancien)"),
                    ("annule", "Annulé (ancien)"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
