# Generated by Django 5.1.15 on 2026-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_created_at_alter_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="operator",
            field=models.CharField(
                choices=[("mtn", "MTN Mobile Money"), ("moov", "Moov Money")],
                default="mtn",
                max_length=20,
            ),
        ),
    ]
