# Generated by Django 5.1.15 on 2026-09-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="chariow_checkout_url",
            field=models.URLField(
                blank=True,
                help_text="URL de paiement sécurisée générée par Chariow",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="chariow_customer_id",
            field=models.CharField(
                blank=True, help_text="Identifiant client Chariow", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="chariow_sale_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant de la vente sur Chariow (ex: sal_xxx)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sebpay_transaction_id",
            field=models.CharField(
                blank=True,
                help_text="Ancien identifiant SebPay (conservé pour historique)",
                max_length=100,
            ),
        ),
    ]
