# Generated by Django 5.1.15 on 2026-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_chariow_checkout_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("moov", "Moov Money"),
                    ("celtiis", "Celtiis Cash"),
                    ("wave", "Wave"),
                    ("card", "Carte bancaire"),
                    ("chariow", "Chariow Multi-Paiement"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
