# Generated by Django 5.2.17 on 2026-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="fedapay_checkout_url",
            field=models.URLField(
                blank=True,
                help_text="URL de paiement sécurisée générée par FedaPay",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="fedapay_transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant de la transaction sur FedaPay (ex: 12345)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="chariow_checkout_url",
            field=models.URLField(
                blank=True,
                help_text="URL de paiement sécurisée générée par Chariow (legacy)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="chariow_sale_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant de la vente sur Chariow (legacy)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mtn", "MTN Mobile Money"),
                    ("moov", "Moov Money"),
                    ("celtiis", "Celtiis Cash"),
                    ("wave", "Wave"),
                    ("card", "Carte bancaire"),
                    ("fedapay", "FedaPay Multi-Paiement"),
                    ("chariow", "Chariow Multi-Paiement (Ancien)"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
