# Generated by Django 5.2.17 on 2026-10-08 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_alter_siteconfiguration_base_exams_count_and_more"),
        ("payments", "0007_payment_fedapay_checkout_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semesteraccess",
            name="academic_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="semesteraccess",
            name="filiere",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.filiere",
            ),
        ),
        migrations.AlterField(
            model_name="semesteraccess",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.level",
            ),
        ),
        migrations.AlterField(
            model_name="semesteraccess",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="academics.school",
            ),
        ),
    ]
