# Generated by Django 6.0.7 on 2026-08-24 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('examen', 'Examen'), ('rattrapage', 'Rattrapage'), ('devoir', 'Devoir'), ('td', 'TD'), ('tp', 'TP'), ('concours', 'Concours'), ('autre', 'Autre')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='exams/')),
                ('is_free', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicyear')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.filiere')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.level')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.subject')),
            ],
        ),
    ]
