# Generated by Django 5.1.15 on 2026-08-26 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_filiere_options_and_more'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.filiere'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='academics.semester'),
        ),
    ]
