# Generated by Django 5.1.15 on 2026-08-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("exams", "0002_alter_exam_filiere_alter_exam_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="correction_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF de la correction (optionnel)",
                null=True,
                upload_to="corrections/",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="summary",
            field=models.ForeignKey(
                blank=True,
                help_text="Fiche résumé rédigée associée (optionnelle)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="content.summary",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="summary_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF du résumé/fiche (optionnel)",
                null=True,
                upload_to="summaries_pdf/",
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.FileField(
                help_text="Fichier PDF de l'épreuve", upload_to="exams/"
            ),
        ),
    ]
