# Generated by Django 5.1.15 on 2026-08-28 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_cloudfile"),
        ("exams", "0003_exam_correction_file_exam_summary_exam_summary_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="cloud_correction_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Fichier Cloud de la correction",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_as_correction",
                to="content.cloudfile",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="cloud_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Fichier Cloud de l'épreuve",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_as_primary",
                to="content.cloudfile",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="cloud_summary_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Fichier Cloud du résumé",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams_as_summary",
                to="content.cloudfile",
            ),
        ),
    ]
