# Generated by Django 5.1.15 on 2026-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_exam_cloud_correction_file_exam_cloud_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_free_correction",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("examen", "Examen"),
                    ("rattrapage", "Rattrapage"),
                    ("devoir", "Devoir"),
                    ("td", "TD"),
                    ("tp", "TP"),
                    ("concours", "Concours"),
                    ("autre", "Autre"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_free",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="exam",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="exam",
            name="year",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
