# Generated by Django 5.2.17 on 2026-10-04 17:03

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_exam_is_free_correction_alter_exam_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="correction_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF de la correction (optionnel)",
                null=True,
                upload_to=exams.models.correction_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="file",
            field=models.FileField(
                help_text="Fichier PDF de l'épreuve",
                upload_to=exams.models.exam_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="exam",
            name="summary_file",
            field=models.FileField(
                blank=True,
                help_text="Fichier PDF du résumé/fiche (optionnel)",
                null=True,
                upload_to=exams.models.summary_upload_to,
            ),
        ),
    ]
