# Generated by Django 5.1.15 on 2026-08-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.PositiveIntegerField(default=4500, help_text="Prix en FCFA"),
        ),
    ]
