# Generated by Django 5.1.15 on 2026-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_alter_subscriptionplan_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.PositiveIntegerField(default=3800, help_text="Prix en FCFA"),
        ),
    ]
